"""added txrxtranceiver and itraceroute test+result classes. added fk names throughout

Revision ID: 0c7f4d7a3ec9
Revises: 123abc456def
Create Date: 2025-04-12 17:31:03.765926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7f4d7a3ec9'
down_revision = '123abc456def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txrxtransceiver_test_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('itraceroute_test_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_test_instance_itraceroute_test', 'itraceroute_test', ['itraceroute_test_id'], ['id'])
        batch_op.create_foreign_key('fk_test_instance_txrxtransceiver_test', 'txrxtransceiver_test', ['txrxtransceiver_test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_instance_txrxtransceiver_test', type_='foreignkey')
        batch_op.drop_constraint('fk_test_instance_itraceroute_test', type_='foreignkey')
        batch_op.drop_column('itraceroute_test_id')
        batch_op.drop_column('txrxtransceiver_test_id')

    # ### end Alembic commands ###
