"""empty message

Revision ID: 153e2f7fad94
Revises: 
Create Date: 2025-04-02 08:36:05.737773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153e2f7fad94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
