"""empty message

Revision ID: 31563a403040
Revises: 6f6f8f1be2bf
Create Date: 2025-04-02 16:48:36.317533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31563a403040'
down_revision = '6f6f8f1be2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
