"""add Ping test models

Revision ID: 53b7b22ad08b
Revises: 72530e0afc68
Create Date: 2025-05-07 21:09:17.292791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b7b22ad08b'
down_revision = '72530e0afc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ping_test_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_test_instance_ping_test', 'ping_test', ['ping_test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_instance_ping_test', type_='foreignkey')
        batch_op.drop_column('ping_test_id')

    # ### end Alembic commands ###
