"""Add log to TestRun

Revision ID: 6f6f8f1be2bf
Revises: 9b3e381de314
Create Date: 2025-04-02 10:36:28.267446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6f8f1be2bf'
down_revision = '9b3e381de314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_column('log')

    # ### end Alembic commands ###
