"""added sfpinfo field to txrxtransceiverTestResult

Revision ID: 791d0f8f1b6b
Revises: 0c7f4d7a3ec9
Create Date: 2025-04-13 09:58:18.722534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d0f8f1b6b'
down_revision = '0c7f4d7a3ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txrxtransceiver_test_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sfpinfo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txrxtransceiver_test_result', schema=None) as batch_op:
        batch_op.drop_column('sfpinfo')

    # ### end Alembic commands ###
