"""add fields created_by and hidden

Revision ID: 82f11b0842a0
Revises: 791d0f8f1b6b
Create Date: 2025-04-17 12:31:30.438669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f11b0842a0'
down_revision = '791d0f8f1b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bgpaspath_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_bgpaspathtest_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_device_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('device_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_devicecredential_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('itraceroute_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_itraceroutetest_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_testrun_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('traceroute_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_traceroutetest_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('txrxtransceiver_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_txrxtransceivertest_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_created_by_id', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('txrxtransceiver_test', schema=None) as batch_op:
        batch_op.drop_constraint('fk_txrxtransceivertest_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('traceroute_test', schema=None) as batch_op:
        batch_op.drop_constraint('fk_traceroutetest_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_constraint('fk_testrun_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('itraceroute_test', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itraceroutetest_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('device_credential', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devicecredential_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint('fk_device_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('hidden')

    with op.batch_alter_table('bgpaspath_test', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bgpaspathtest_created_by_id', type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
