"""add Custom Show Command test

Revision ID: 870b9bb6d0c6
Revises: cf14bda380c7
Create Date: 2025-06-13 16:35:08.527525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870b9bb6d0c6'
down_revision = 'cf14bda380c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customshowcommand_test_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_test_instance_customshowcommand_test', 'customshowcommand_test', ['customshowcommand_test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_instance_customshowcommand_test', type_='foreignkey')
        batch_op.drop_column('customshowcommand_test_id')

    # ### end Alembic commands ###
