"""empty message

Revision ID: 9b3e381de314
Revises: 153e2f7fad94
Create Date: 2025-04-02 08:52:59.150919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3e381de314'
down_revision = '153e2f7fad94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_active_at_run', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_instance', schema=None) as batch_op:
        batch_op.drop_column('device_active_at_run')

    # ### end Alembic commands ###
