"""Add user_timezone to User model

Revision ID: cf14bda380c7
Revises: 7fb2e30896dd
Create Date: 2025-05-27 15:20:59.925076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf14bda380c7'
down_revision = '7fb2e30896dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_timezone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_timezone')

    # ### end Alembic commands ###
