"""updated TestGroup relationships

Revision ID: e9dd9d26241e
Revises: 53b7b22ad08b
Create Date: 2025-05-21 08:47:26.180668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dd9d26241e'
down_revision = '53b7b22ad08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_group_association', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_test_group', ['test_id', 'test_type', 'group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_group_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_test_group', type_='unique')

    # ### end Alembic commands ###
